# FROM node:22-alpine

# WORKDIR /app
# RUN apk add --no-cache curl

# COPY package*.json ./
# RUN npm ci
# COPY . .

# RUN addgroup -S app && adduser -S app -G app
# RUN chown -R app:app /app
# USER app

# EXPOSE 5173
# HEALTHCHECK --interval=30s --retries=3 --timeout=30s --start-interval=5s --start-period=5s \
#   CMD curl -f http://localhost:5173 || exit 1

# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
# ---- build stage ----
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ---- serve stage ----
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
RUN apk add --no-cache curl
HEALTHCHECK --interval=30s --retries=3 --timeout=10s CMD curl -f http://localhost/ || exit 1