FROM node:22-alpine AS builder

WORKDIR /app
RUN apk add --no-cache curl
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
RUN addgroup -S app && adduser -S app -G app
USER app
COPY --chown=app:app . .
HEALTHCHECK --interval=30s --retries=3 --timeout=30s --start-interval=5s --start-period=5s\
 CMD [ "curl -f http://localhost:3000" ]
CMD [ "npm","run","start" ]

